---
fixtures:
  repositories:
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat'
      ref: v9.0.0
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
      ref: v9.4.0
    host_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-host_core'
      ref: v1.2.0
  symlinks:
    dnsmasq: "#{source_dir}"
